
services:
  fastapi:
    build: .
    container_name: fastapi_app
    ports:
      - "8000:8000"
    env_file:
      - .env

  celery_worker:
    build:
      context: .
      dockerfile: Dockerfile.celery
    container_name: celery_worker
    depends_on:
      - fastapi
    env_file:
      - .env
